"use strict";
exports.__esModule = true;
var categoryController_1 = require("../controllers/categoryController");
var validationMiddleware_1 = require("../middleware/validationMiddleware");
var express = require("express");
var router = express.Router();
router.post("/categories", validationMiddleware_1.validationMiddleware.validateInput, categoryController_1.CategoryController.createCategory);
router.get("/categories", categoryController_1.CategoryController.readCategories);
router["delete"]("/categories/:id", validationMiddleware_1.validationMiddleware.validateId, categoryController_1.CategoryController.deleteCategory);
router.get("/categories/:id", validationMiddleware_1.validationMiddleware.validateId, categoryController_1.CategoryController.readCategory);
router.patch("/categories/:id", validationMiddleware_1.validationMiddleware.validateId, validationMiddleware_1.validationMiddleware.validateInput, categoryController_1.CategoryController.updateCategory);
exports["default"] = router;
